<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net10.0-windows10.0.18362;</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <RootNamespace>Humbatt.UI.Toolkit.WPF</RootNamespace>
    <Description>Metro styled, via MahApps, controls and classess for Humbatt.UI.Toolkit.WPF for .Net Core 3.x and Net 5+</Description>
    <PackageTags>WPF Controls</PackageTags>
    <PackageReleaseNotes>Added support for .NET 10.0</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Humbatt.UI.Toolkit.WPF\Humbatt.UI.Toolkit.WPF.csproj" />
  </ItemGroup>

</Project>
