<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net10.0-windows10.0.18362;</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <Description>Mvmm based controls and classess for Humbatt.UI.Toolkit.WPF for .Net Core 3.x and Net 5+</Description>
    <PackageTags>WPF Controls</PackageTags>
    <PackageReleaseNotes>Added support for .NET 10.0</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DSoft.System.Mvvm" Version="3.5.2511.161" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Humbatt.UI.Toolkit.WPF\Humbatt.UI.Toolkit.WPF.csproj" />
  </ItemGroup>

</Project>
