<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <Description>Common shared classes for Humbatt.UI.Toolkit</Description>
    <PackageTags>WPF Controls</PackageTags>
    <PackageReleaseNotes>Added support for .NET 10.0 and Option Item support</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

</Project>
