<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows10.0.19041.0;</TargetFrameworks>
    <RootNamespace>Humbatt.UI.Toolkit.WinUI</RootNamespace>
    <Description>WinUI UI controls, extensions and helpers for .NET 8.0+</Description>
    <PackageTags>WinUI</PackageTags>
    <PackageReleaseNotes>Added support for .NET 10.0</PackageReleaseNotes>
    <Configurations>Debug;Release</Configurations>
    <WinUISDKReferences>false</WinUISDKReferences>
  </PropertyGroup>

  <PropertyGroup>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <DefineConstants>$(DefineConstants);WINUI</DefineConstants>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7175" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.0" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Humbatt.UI.Toolkit.Core\Humbatt.UI.Toolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Editors\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
